export const REDUCER_NAME = "movies";
export const SET_MOVIES = `${REDUCER_NAME}/SET_MOVIES`;
export const SET_FILTERS = `${REDUCER_NAME}/SET_FILTERS`;
export const RESET_FILTERS = `${REDUCER_NAME}/RESET_FILTERS`;
export const SET_ERROR = `${REDUCER_NAME}/SET_ERROR`;
export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
